title:   Ryan Stowers
logo: "/images/Profile Pic 1.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  As a data enthusiast, I enjoy using Python, Power BI, and Tableau to uncover valuable insights. I have delivered key findings and trends in diverse projects, utilizing a range of data analysis functions. With Power BI and Tableau, I have created various charts and graphs, from lollipop charts to timeline graphs, using different metrics. I am passionate about exploring the different aspects of data and continuously seeking to expand my knowledge to achieve great things.
  <br><br><br>
  <a href="https://www.linkedin.com/in/ryan-stowers-017523197/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://public.tableau.com/app/profile/ryan.stowers">View My Tableau Work Samples</a>
  <br><br>
  
   
 
