title:   Ryan Stowers
logo: "/images/Profile Pic 1.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  As an As a data enthusiast, I find great satisfaction in leveraging data to uncover valuable insights across a range of activities. I have engaged in various projects where I was responsible for delivering key findings and trends. Using Python, I have explored, cleaned, and analyzed data utilizing a diverse range of functions that are specific to various encounters. I have also used Power BI and Tableau using many different metrics to visualize many charts and graphs ranging from lollipop charts to timeline graphs. I take pleasure in exploring the different aspects of data and continuously seek to expand my knowledge and understanding of how data can be leveraged to accomplish great things.
  <br><br><br>
  <a href="https://www.linkedin.com/in/ryan-stowers-017523197/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://public.tableau.com/app/profile/ryan.stowers">View My Tableau Work Samples</a>
  <br><br>
  <a href="https://ryanstowers.notion.site/Portfolio-Ryan-Stowers-50a71750f98d4e7da432354e65e85386">View My Notion Portfolios</a>
  <br><br>
  <br><br>
theme: jekyll-theme-minimal   
 
